url: https://hackriver.github.io
baseurl: 

# Site settings
title: hack.river
email: contato@hackriver.com.br
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Renan Valentin Ferreira
  pic: renan
  position:
  social:
    - title: twitter
      url: https://twitter.com/nantoaqui
    - title: github
      url: https://github.com/renanvalentin
    - title: linkedin
      url: https://br.linkedin.com/in/renanvalentin

- name: Leandro Cesquini Pereira
  pic: leandro
  position:
  social:
    - title: twitter
      url: https://twitter.com/leandrocesquini
    - title: github
      url: http://github.com/leandrocp/
    - title: linkedin
      url: https://br.linkedin.com/in/leandrocesquini

- name: Marco Bonuto
  pic: marco
  position:
  social:
    - title: github
      url: https://github.com/marcobonuto
    - title: linkedin
      url: https://br.linkedin.com/in/marco-bonuto-219954aa

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: group
    url: http://www.meetup.com/hack-river/
  - title: slack
    url: http://slack.hackriver.com.br
  - title: facebook
    url: http://facebook.com/hackriver
  - title: github
    url: http://github.com/hackriver
  - title: bullhorn
    url: http://speakerdeck.com/hackriver

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
